<!doctype html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="utf-8">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>     
        <script>
            
            window.onload = function() {        
                // resolve1!!をreturnしているため、この値がresolveされる
                async function resolveSample() {
                    return '★resolve!!';
                }

                // resolveSampleがPromiseを返し、resolve!!がresolveされるため
                // then()が実行されコンソールにresolve!!が表示される
                resolveSample().then(value => {
                    console.log(value); // => resolve!!
                    $("#resolveSample").text(value);
                });


                // reject!!をthrowしているため、この値がrejectされる
                async function rejectSample() {
                    throw new Error('★reject!!');
                }

                // rejectSampleがPromiseを返し、reject!!がrejectされるため
                // catch()が実行されコンソールにreject!!が表示される
                rejectSample().catch(err => {
                    console.log(err); // => reject!!
                    $("#rejectSample").text(err);
                });
                
                
                // reject!!をthrowしているため、この値がrejectされる
                async function Sample() {
                    throw new Error('★Sample!!');
                }
                Sample()
                    .then(value => {
                        console.log(value);
                        $("#resolveSample").text(value);
                    })
                    .catch(err => {
                        console.log(err);
                        $("#rejectSample").text(err);
                    });
                
                
    
            };
        </script>
    </head>
    <body>
        <div>
            こんにちは、
        </div>
<pre>
// resolve1!!をreturnしているため、この値がresolveされる
async function resolveSample() {
    return '★resolve!!';
}

// resolveSampleがPromiseを返し、resolve!!がresolveされるため
// then()が実行されコンソールにresolve!!が表示される
resolveSample().then(value => {
    $("#resolveSample").text(value);
});
</pre>
        <h1 id="resolveSample"></h1>
<pre>
// reject!!をthrowしているため、この値がrejectされる
async function rejectSample() {
    throw new Error('★reject!!');
}

// rejectSampleがPromiseを返し、reject!!がrejectされるため
// catch()が実行されコンソールにreject!!が表示される
rejectSample().catch(err => {
    console.log(err); // => reject!!
    $("#rejectSample").text(err);
});
</pre>
        <h1 id="rejectSample"></h1>
    </body>
</html>
