<!doctype html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="utf-8">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>     
        <script>
            
            window.onload = function() {        

                async function Sample(error) {
                    if(error){
                        // throwしているため、この値がrejectされる
                        throw new Error('★Error★');
                    }
                    else{
                        // returnしているため、この値がresolveされる
                        return '★Success★';
                    }   
                }
                                
                (async function(flag) {
                    try {
                        var result = await Sample(flag);
                        $("#Sample1").text(result);  
                    } catch (error) {
                        $("#Sample1").text(error);
                        $('#Sample1').css('color','red');
                    }
                })(true);
                
                (async function(flag) {
                    try {
                        var result = await Sample(flag);
                        $("#Sample2").text(result);  
                    } catch (error) {
                        $("#Sample2").text(error);
                        $('#Sample2').css('color','red');
                    }
                })(false);
            };
        </script>
    </head>
    <body>
        <div>
            こんにちは、
        </div>
<pre>
async function Sample(error) {
    if(error){
        throw new Error('★Error★');
    }
    else{
        return '★Sample★';
    }   
}
</pre>
<hr/>
<h1>rejectサンプル</h1>
awaitを使うと同期型になる。
Sampleでthrowされたので、catchルートを通る。
<pre>
(async function(flag) {
    try {
        var result = await Sample(flag);
        $("#Sample1").text(result);  
    } catch (error) {
        $("#Sample1").text(error);
        $('#Sample1').css('color','red');
    }
})(true);
</pre>
<h1 id="Sample1"></h1>
<hr/>
<h1>resolveサンプル</h1>
awaitを使うと同期型になる。
Sampleでreturnされたので、例外は発生しない。
<pre>
(async function(flag) {
    try {
        var result = await Sample(flag);
        $("#Sample2").text(result);  
    } catch (error) {
        $("#Sample2").text(error);
        $('#Sample2').css('color','red');
    }
})(false);
</pre>
<h1 id="Sample2"></h1>

    </body>
</html>
